In [6]:
import numpy as np

In [52]:
a=np.arange(0,21)

In [53]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [54]:
a=np.arange(0,21,2)

In [55]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [56]:
a=np.arange(0,21,3)

In [57]:
a

array([ 0,  3,  6,  9, 12, 15, 18])